# Generated by Django 4.1.7 on 2023-09-12 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('coach', models.CharField(max_length=100)),
                ('student', models.CharField(blank=True, max_length=100)),
                ('lesson_type', models.CharField(max_length=200)),
                ('wage', models.FloatField()),
                ('submitted', models.BooleanField(default=False)),
                ('earning', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
