# Generated by Django 4.2.5 on 2023-09-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_tentenemployee_details_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenTenHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('employee', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('wage', models.FloatField()),
                ('submitted', models.BooleanField(default=False)),
                ('earning', models.FloatField(blank=True, null=True)),
                ('school', models.CharField(max_length=100)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.employmentdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VtcHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('employee', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('wage', models.FloatField()),
                ('submitted', models.BooleanField(default=False)),
                ('earning', models.FloatField(blank=True, null=True)),
                ('student', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
