# Generated by Django 4.2.5 on 2023-09-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_tentenemployee_details_and_more'),
        ('main', '0002_tentenhour_vtchour_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtchour',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.employmentdetails'),
            preserve_default=False,
        ),
    ]
