# Generated by Django 4.2.5 on 2023-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vtchour_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentenhour',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vtchour',
            name='student',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
