# Generated by Django 4.2.5 on 2023-09-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_tentenemployee_details_and_more'),
        ('main', '0004_alter_tentenhour_school_alter_vtchour_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentenhour',
            name='details',
        ),
        migrations.RemoveField(
            model_name='vtchour',
            name='details',
        ),
        migrations.AddField(
            model_name='tentenhour',
            name='ten_ten_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.tentenemployee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vtchour',
            name='vtc_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.vtcemployee'),
            preserve_default=False,
        ),
    ]
