# Generated by Django 4.2.5 on 2023-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_is_ten_ten_employmentdetails_is_ten_ten_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetails',
            name='first_login',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
