# Generated by Django 4.2.5 on 2023-09-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_employmentdetails_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentenemployee',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ten_ten_details', to='registration.employmentdetails'),
        ),
        migrations.AlterField(
            model_name='vtcemployee',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vtc_details', to='registration.employmentdetails'),
        ),
    ]
